name: rna
channels:
  - conda-forge
  - bioconda

dependencies:
  - bedops
  - bedtools
  - bioconductor-GenomicRanges
  - bioconductor-orthology.eg.db
  - bioconductor-TxDb.Mmusculus.UCSC.mm10.ensGene
  - bioconductor-TxDb.Hsapiens.UCSC.hg38.knownGene
  - bioconductor-TxDb.Mmusculus.UCSC.mm10.knownGene
  - bioconductor-complexheatmap
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-sva
  - bioconductor-fgsea
  - bioconductor-ruvseq
  - bioconductor-rsamtools
  - bioconductor-tximport
  - r-msigdbr
  - r-enrichr
  - salmon
  - r-pheatmap
  - r-rstatix
  - rseqc
