name: Snakemake CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        use-mamba: true

    - name: Create Conda Environment
      run: |
        mamba env create -f ./config/rna_env.yaml
